In [1]:
a = [1, 2, 3]
a [:0] = 10

TypeError: can only assign an iterable

In [2]:
a[:0] = [10]

In [3]:
print a

[10, 1, 2, 3]


In [4]:
a[:0]

[]

In [5]:
a[0]

10

In [6]:
L = [1, ['a', ['x', 'y'], 'b'], 3]
print L[0]
print L[1]
print L[1][1]
print L[1][1][1]
# 시험문제내기 되게 좋은것!

1
['a', ['x', 'y'], 'b']
['x', 'y']
y


In [15]:
sun, mon, tue, wed, thu, fri, sat = range(7)
#(sun, mon, tue, wed, thu, fri, sat) = range(7) 이거랑 같은말!

In [10]:
sun

0

In [11]:
mon

1

In [13]:
a = sun, mon, tue, wed, thu, fri, sat

In [14]:
type(a)

tuple

In [16]:
(a, b) = [1, 2]
print a
print b

1
2


In [17]:
s = [1, 2, 3]

s.append(5) # 리스트 맨 마지막에 정수 값 5 추가
print s

s.insert(3, 4) # 3 인덱스 위치에 정수 값 4 추가
print s

[1, 2, 3, 5]
[1, 2, 3, 4, 5]


In [18]:
s = [1, 2, 3, 4, 5]

print s.index(3)        # 값 3의 인덱스 반환

print s.count(2)        # 값 2의 개수 반환

s = [1, 2, 2, 2, 2, 2, 3, 4, 5]
print s.count(2)

2
1
5


In [19]:
s = [1, 2, -10, -7, 100]
s.sort()
print s

[-10, -7, 1, 2, 100]


In [21]:
print s.sort()
#sort함수는 반환값이 없다

None


In [22]:
#extend()와 append()의 차이
#append는 리스트 자체가 원소로 들어감
#extend는 기존 리스트를 확장하는 개념
s.extend([60, 70]) # 새로운 리스트([60, 70]를 기존 리스트 s 뒤에 병합
print s

s.append([60, 70]) # 주의: append로 새로운 리스트를 추가하면 하나의 자료 요소로서 추가
print s

[-10, -7, 1, 2, 100, 60, 70]
[-10, -7, 1, 2, 100, 60, 70, [60, 70]]


In [26]:
s = [10, 20, 30, 40, 50]
print s

s.extend([60, 70])
print s

s.extend((100, 200))
print s

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 60, 70]
[10, 20, 30, 40, 50, 60, 70, 100, 200]


In [27]:
s.extend?

In [28]:
def mycmp(a1, a2):
    return cmp(a2, a1)

In [29]:
mycmp

<function __main__.mycmp>

In [30]:
L = [1, 5, 3, 2, 4, 6]
L.sort(mycmp)

In [31]:
print L

[6, 5, 4, 3, 2, 1]


In [32]:
def cmp_1(a1, a2):
    return cmp(a1[1], a2[1])

def cmp_2(a1, a2):
    return cmp(a1[2], a2[2])

L = [ ('lee', 5, 38), ('kim', 3, 28), ('jung', 10, 36)]
L.sort()
print 'sorted by name:', L

L.sort(cmp_1)
print 'sorted by experience:', L

L.sort(cmp_2)
print 'sorted by age:', L

sorted by name: [('jung', 10, 36), ('kim', 3, 28), ('lee', 5, 38)]
sorted by experience: [('kim', 3, 28), ('lee', 5, 38), ('jung', 10, 36)]
sorted by age: [('kim', 3, 28), ('jung', 10, 36), ('lee', 5, 38)]


In [33]:
L = [1, 6, 3, 8, 6, 2, 9]
L.sort(reverse = True)
print L

[9, 8, 6, 6, 3, 2, 1]


In [34]:
L = ['123', '34', '56', '2345'] #문자열로 소팅
L.sort()
print L

L.sort(key=int)
print L

['123', '2345', '34', '56']
['34', '56', '123', '2345']


In [35]:
L.sort?

In [36]:
L.sort(cmp=mycmp) #첫번째 인자는 cmp 생략 가능

In [38]:
L.sort(key = int) #두번째 인자부터는 key= , reverse = 같은걸 꼭 써줘야됨

In [39]:
#리스트 내포 리터럴 시험에 나올 예정!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [41]:
[(x,y,z) for x in range(1, 30) for y in range(x,30) for z in range(y, 30) if x**2 + y**2 == z**2]

[(3, 4, 5),
 (5, 12, 13),
 (6, 8, 10),
 (7, 24, 25),
 (8, 15, 17),
 (9, 12, 15),
 (10, 24, 26),
 (12, 16, 20),
 (15, 20, 25),
 (20, 21, 29)]

In [42]:
list_a = ['A', 'B']
list_b = ['C', 'D']
print [x+y for x in list_a for y in list_b]
print
print [[x+y for x in list_a] for y in list_b]

['AC', 'AD', 'BC', 'BD']

[['AC', 'BC'], ['AD', 'BD']]


In [43]:
l = []
for y in list_b:
    l2 = []
    for x in list_a:
        l2.append(x+y)
    l.append(l2)
print l

[['AC', 'BC'], ['AD', 'BD']]


In [44]:
from numpy import *
a = array(((1,2,3), (4,5,6), (7, 8, 9))) # 3*3 행렬 생성
print a
print

b = zeros((3,3))
print b
print

c = ones((3,3))
print c
print

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]



In [45]:
f = a + c     # 각 원소들끼리의 덧셈
print f
print

d = a * a     # 각 원소들끼리의 곱셈
print d
print

e = dot(a, c) # 일반적인 행렬 곱셈 
print e
print

[[  2.   3.   4.]
 [  5.   6.   7.]
 [  8.   9.  10.]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

[[  6.   6.   6.]
 [ 15.  15.  15.]
 [ 24.  24.  24.]]



In [46]:
from numpy.linalg import *
g = inv(a)
print g
print

h = eig(a) #고유벡터구하는방식
print h
print

[[ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]
 [  9.00719925e+15  -1.80143985e+16   9.00719925e+15]
 [ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]]

(array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))



In [47]:
print __name__      # 로컬 이름 
print

print __doc__       # 로컬에 지정된 문서문자열
print

__main__

Automatically created module for IPython interactive environment



In [48]:
import math

print "math.__name__: ", math.__name__
print
print dir(math)  # dir() 내장 함수에 모듈을 인자로 전달하면 해당 모듈이 지원하는 멤버 변수 및 함수 목록을 얻는다.
print
print "math.__doc__:", math.__doc__
print
print "math.log10.__doc__: ", math.log10.__doc__

math.__name__:  math

['__doc__', '__name__', '__package__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'hypot', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'modf', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']

math.__doc__: This module is always available.  It provides access to the
mathematical functions defined by the C standard.

math.log10.__doc__:  log10(x)

Return the base 10 logarithm of x.


In [49]:
math?

In [51]:
# 명령행 인수

In [55]:
# file: arg.py
import sys
#소스내용
print sys.argv

['C:\\Users\\Heejeong\\AppData\\Local\\Enthought\\Canopy\\User\\lib\\site-packages\\IPython\\kernel\\__main__.py', '-f', 'C:\\Users\\Heejeong\\.ipython\\profile_default\\security\\kernel-8896f9c0-847f-434c-af7c-5ee1152e495a.json', '--profile-dir', 'C:\\Users\\Heejeong\\.ipython\\profile_default']


In [53]:
# public static void main(string[] arg) {  }
# int main(int argc, char** argv) {  }  
# argc는 인자 갯수, argv는 ??

In [57]:
# python arg.py -l -a -v a b c
#sys.argv는 리스트이고, 처음에는 파일명의 풀패스를 같이 보여주고, 원소들을 찍어준다.
#명령행 인자중에 첫번쨰 인자를 찍고싶다면? print sys.argv[1]